# Generated by Django 5.1.7 on 2025-03-22 18:30

import documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='documents/', validators=[documents.models.validate_document_type]),
        ),
    ]
